language: python
python:
  - "3.5"
  - "3.6"
# command to install dependencies
install:
  - pip3 install setuptools
  - python3 setup.py install
# command to run tests
script:
  - python3 ci_scripts/test.py
